<form id="post" action="?r=addpost" method="post">
    <label for="title">Title:</label>
    <input id="title" type="text" name="title" placeholder="title" /><br />
    <label for="discription">Discription:</label><br />
    <textarea form="post" name="discription" type="textarea" name="discription" cols="100" rows="20"></textarea><br />
    <input type="submit" value="Add Post"/><br />
    <a href="?r=registration">Regisration</a>
    <a href="?r=login">Login</a>
    <a href="?r=showpost">ShowPost</a>
</form>

